[project]
name = "google-ai"
version = "0.1.0"
description = "Google AI Gemini 2 Examples"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = [
    "google-genai>=0.2.2",
    "ipykernel>=6.29.5",
    "langgraph>=0.2.59",
    "matplotlib>=3.10.0",
    "pillow>=11.0.0",
]
