[project]
name = "kumo-hm"
version = "0.1.0"
description = "Environment for Kumo H&M demo."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "db-dtypes>=1.4.3",
    "google-auth>=2.40.2",
    "google-cloud-bigquery>=3.33.0",
    "ipykernel>=6.29.5",
    "kaggle>=1.7.4.5",
    "kumoai>=2.1.0",
    "relbench>=1.1.0",
]
